In [33]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\himan\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\himan\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\himan\AppData\Roaming\Python\Python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\himan\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\himan\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

Pandas is an open-source Python library designed for data manipulation and analysis, widely regarded as a fundamental tool in the data science ecosystem.  It provides high-performance, flexible data structures specifically engineered to handle structured, tabular data, making it easier to clean, transform, and analyze datasets compared to raw Python lists or dictionaries.     


Key applications of Pandas in data science include:

Data Cleaning and Preprocessing: It offers robust functions to handle missing values (via dropna and fillna), remove duplicates, and transform data types, which is critical since real-world data is often messy. 
Data Exploration and Analysis: Users can quickly calculate summary statistics (mean, median, standard deviation), filter subsets of data based on conditions, and perform grouping and aggregation operations to uncover insights. 
Data Transformation: Pandas facilitates reshaping, pivoting, and merging datasets from various sources (CSV, Excel, SQL) using functions like merge, concat, and pivot_table. 
Integration with the PyData Ecosystem: It integrates seamlessly with other libraries, feeding cleaned data into NumPy for numerical operations, Matplotlib/Seaborn for visualization, and Scikit-learn for machine learning modeling.

In [34]:
import os 
import numpy as np 
import pandas as pd

In [35]:
df = pd.read_csv(r"C:\Users\himan\Desktop\Datascience\pandas\Used_Bikes.csv")

In [36]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [37]:
df.head(10) #print the starting first 5 data by default
#10 is the no. of data you want to get printed

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield

In [38]:
df.tail(10)

,bike_name,price,city,kms_driven,owner,age,power,brand
32638,Yamaha Fazer 25 250cc,123000.0,Kadapa,14500.0,First Owner,4.0,250.0,Yamaha
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [40]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [41]:
df["brand"] #particular columns

0                  TVS
1        Royal Enfield
2              Triumph
3                  TVS
4               Yamaha
             ...
32643             Hero
32644              TVS
32645            Bajaj
32646             Hero
32647            Bajaj
Name: brand, Length: 32648, dtype: str

In [42]:
df[["brand"]]

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [43]:
df[["owner"]]

             owner
0      First Owner
1      First Owner
2      First Owner
3      First Owner
4      First Owner
...            ...
32643  First Owner
32644  First Owner
32645  First Owner
32646  First Owner
32647  First Owner

[32648 rows x 1 columns]

In [44]:
df[["owner", "brand", "price"]]

             owner          brand     price
0      First Owner            TVS   35000.0
1      First Owner  Royal Enfield  119900.0
2      First Owner        Triumph  600000.0
3      First Owner            TVS   65000.0
4      First Owner         Yamaha   80000.0
...            ...            ...       ...
32643  First Owner           Hero   39000.0
32644  First Owner            TVS   30000.0
32645  First Owner          Bajaj   60000.0
32646  First Owner           Hero   15600.0
32647  First Owner          Bajaj   22000.0

[32648 rows x 3 columns]

In [45]:
df["brand"].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [46]:
df["age"].unique()
df["age"].nunique()#no. of total no. of ages

35

In [47]:
df["brand"].value_counts()

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [48]:
df.duplicated().sum()

np.int64(25324)

In [49]:
df.drop_duplicates().sum()

bike_name     TVS Star City Plus Dual Tone 110ccRoyal Enfiel...
price                                               621689684.0
city          AhmedabadDelhiDelhiBangaloreBangaloreDelhiDelh...
kms_driven                                          175120477.0
owner         First OwnerFirst OwnerFirst OwnerFirst OwnerFi...
age                                                     48752.0
power                                                 1670849.0
brand         TVSRoyal EnfieldTriumphTVSYamahaYamahaHondaHer...
dtype: object

In [50]:
df.drop_duplicates(inplace=True)

In [51]:
df.drop_duplicates().sum()

bike_name     TVS Star City Plus Dual Tone 110ccRoyal Enfiel...
price                                               621689684.0
city          AhmedabadDelhiDelhiBangaloreBangaloreDelhiDelh...
kms_driven                                          175120477.0
owner         First OwnerFirst OwnerFirst OwnerFirst OwnerFi...
age                                                     48752.0
power                                                 1670849.0
brand         TVSRoyal EnfieldTriumphTVSYamahaYamahaHondaHer...
dtype: object

In [52]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [53]:
df.dropna(inplace=True)

In [54]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [55]:
owner_dict={'First owner':1,'Second owner':2,'Third owner':3,'Fourth owner or more ':4}

In [56]:
df['owner']=df['owner'].map(owner_dict)

In [57]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,NaN,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,NaN,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,NaN,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,NaN,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,NaN,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,NaN,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,NaN,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,NaN,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,NaN,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,NaN,5.0,220.0,Bajaj

In [58]:
# df.drop('city',axis=1,inplace=True)# axis 1 is column 0 is rows

In [59]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,NaN,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,NaN,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,NaN,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,NaN,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,NaN,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,NaN,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,NaN,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,NaN,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,NaN,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,NaN,5.0,220.0,Bajaj

In [60]:
# df.drop('bike_name',axis=1,inplace=True)

In [61]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,NaN,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,NaN,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,NaN,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,NaN,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,NaN,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,NaN,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,NaN,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,NaN,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,NaN,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,NaN,5.0,220.0,Bajaj

In [68]:
df.drop(['city','bike_name'], axis=1, inplace=True, errors='ignore')

In [66]:
df

         price  kms_driven  owner  age  power            brand
0      35000.0     17654.0    NaN  3.0  110.0              TVS
1     119900.0     11000.0    NaN  4.0  350.0    Royal Enfield
2     600000.0       110.0    NaN  8.0  675.0          Triumph
3      65000.0     16329.0    NaN  4.0  180.0              TVS
4      80000.0     10000.0    NaN  3.0  150.0           Yamaha
...        ...         ...    ...  ...    ...              ...
9362   25000.0     48587.0    NaN  8.0  150.0             Hero
9369   35000.0     60000.0    NaN  9.0  220.0            Bajaj
9370  450000.0      3430.0    NaN  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0    NaN  4.0  400.0            Bajaj
9372   80000.0      7127.0    NaN  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [69]:
brand_dict = {
     'TVS':1, 'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23
}

In [70]:
df['brand']=df['brand'].map(brand_dict)

In [71]:
df

         price  kms_driven  owner  age  power  brand
0      35000.0     17654.0    NaN  3.0  110.0      1
1     119900.0     11000.0    NaN  4.0  350.0      2
2     600000.0       110.0    NaN  8.0  675.0      3
3      65000.0     16329.0    NaN  4.0  180.0      1
4      80000.0     10000.0    NaN  3.0  150.0      4
...        ...         ...    ...  ...    ...    ...
9362   25000.0     48587.0    NaN  8.0  150.0      6
9369   35000.0     60000.0    NaN  9.0  220.0      7
9370  450000.0      3430.0    NaN  4.0  750.0     15
9371  139000.0     21300.0    NaN  4.0  400.0      7
9372   80000.0      7127.0    NaN  5.0  220.0      7

[7324 rows x 6 columns]